import type { Metadata } from "next";
import Link from "next/link";
import { HOODFLOW_DCA_ADDRESS, PERMIT2_ADDRESS, UNIVERSAL_ROUTER_ADDRESS, USDG_ADDRESS } from "@/lib/hoodflow-mainnet";

export const metadata: Metadata = {
  title: "Security, Contracts & Trading Protections",
  description: "Review HoodFlow's Robinhood Chain contracts, router addresses, slippage protection, permission model, audit status and known limitations.",
  alternates: { canonical: "/security" },
};

const explorer = "https://robinhoodchain.blockscout.com/address/";
const sourceRepository = "https://github.com/dereliapps/hoodflow";

export default function SecurityPage() {
  return <main className="seo-shell">
    <header className="seo-nav"><Link href="/" className="seo-logo">hoodflow<span>MAINNET BETA</span></Link><nav><Link href="/stock-tokens">Markets</Link><Link href="/docs">Docs</Link><a href={sourceRepository} target="_blank" rel="noreferrer">Source</a><Link href="/how-it-works">How it works</Link><Link href="/?view=assets" className="seo-cta">Open app</Link></nav></header>
    <section className="seo-hero security-hero"><p>SECURITY & TRANSPARENCY</p><h1>Verify the system.<br /><em>Then verify the order.</em></h1><div><p>HoodFlow exposes the code, contracts, route rules and limitations that matter before a wallet signature. The independent audit is still pending; source review and responsible disclosure are open now.</p><span>Audit pending · source public · disclosure open</span></div></section>
    <section className="security-status"><div><span>INTERFACE</span><strong>MAINNET BETA</strong><p>Direct Buy and Sell are enabled only for reviewed full-fill routes.</p></div><div><span>INDEPENDENT AUDIT</span><strong className="pending">PENDING</strong><p>No audit badge is shown before a public final report and remediation log exist.</p></div><div><span>CUSTODY</span><strong>SELF-CUSTODY</strong><p>HoodFlow does not hold wallet keys or purchased tokens.</p></div></section>
    <section className="security-evidence"><div className="security-evidence-head"><p>TRUST SIGNALS AVAILABLE TODAY</p><h2>Audit pending does not mean<br />evidence unavailable.</h2></div><div className="security-evidence-grid"><article><span>01</span><h3>Public contract source</h3><p>Review the DCA engine, adapters, tests and deployment configuration without relying on a marketing badge.</p><a href={`${sourceRepository}/tree/main/contracts`} target="_blank" rel="noreferrer">Open contracts ↗</a></article><article><span>02</span><h3>Automated security checks</h3><p>Contract and release suites run on each change. Code scanning helps catch regressions but is not presented as an audit.</p><a href={`${sourceRepository}/actions`} target="_blank" rel="noreferrer">View checks ↗</a></article><article><span>03</span><h3>Responsible disclosure</h3><p>A public security policy defines private intake, scope, response target and safe-testing rules. No reward is implied before a funded bounty exists.</p><a href={`${sourceRepository}/security/policy`} target="_blank" rel="noreferrer">Read reporting policy ↗</a></article><article><span>04</span><h3>Team identity</h3><p>The operator is currently pseudonymous and is not presented as doxxed or independently identity-verified.</p><a href="https://x.com/hoodfloow" target="_blank" rel="noreferrer">Official X account ↗</a></article></div></section>
    <section className="security-addresses"><h2>Addresses used by the interface</h2><div><span>USDG</span><a href={`${explorer}${USDG_ADDRESS}`} target="_blank" rel="noreferrer">{USDG_ADDRESS} ↗</a></div><div><span>Permit2</span><a href={`${explorer}${PERMIT2_ADDRESS}`} target="_blank" rel="noreferrer">{PERMIT2_ADDRESS} ↗</a></div><div><span>Universal Router</span><a href={`${explorer}${UNIVERSAL_ROUTER_ADDRESS}`} target="_blank" rel="noreferrer">{UNIVERSAL_ROUTER_ADDRESS} ↗</a></div><div><span>DCA engine</span><a href={`${explorer}${HOODFLOW_DCA_ADDRESS}`} target="_blank" rel="noreferrer">{HOODFLOW_DCA_ADDRESS} ↗</a></div></section>
    <section className="seo-content-grid"><article><span>01</span><h2>Minimum output</h2><p>Minimum received equals the executable quote multiplied by one minus your selected slippage. The router call fails if the protected amount cannot be delivered.</p></article><article><span>02</span><h2>Short-lived permission</h2><p>Permit2 signs the selected amount with a ten-minute expiration. Review the token, spender, amount and deadline in your wallet.</p></article><article><span>03</span><h2>Route gating</h2><p>Watch-only assets remain visible but cannot be traded until a complete-input fork execution passes and a fresh quote is available.</p></article></section>
    <section className="known-risks"><h2>Known limitations</h2><ul><li>Smart contracts and interfaces can contain undiscovered vulnerabilities.</li><li>The independent audit is pending; automated tests and public source do not replace it.</li><li>No funded public bug bounty has been announced yet.</li><li>The operator is pseudonymous and not independently identity-verified.</li><li>The DCA engine is currently controlled by a single externally owned wallet; a multisig or timelock is not yet verified.</li><li>Oracle reference prices can be delayed when underlying markets are closed.</li><li>DEX liquidity can move between the quote and wallet confirmation.</li><li>Stock Tokens are not shares and may be restricted by jurisdiction.</li><li>Robinhood Chain, RPC providers, routers and wallets are third-party systems.</li></ul><a href={`${sourceRepository}/blob/main/AUDIT_SCOPE.md`} target="_blank" rel="noreferrer">Read the auditor scope brief ↗</a><Link href="/?view=controls">Open live controller and RPC status →</Link></section>
    <section className="seo-risk"><strong>Independent product</strong><p>HoodFlow is built on Robinhood Chain but is not affiliated with or endorsed by Robinhood Markets, Inc.</p></section>
    <footer className="seo-footer"><Link href="/docs">Read the documentation</Link><Link href="/roadmap">View Mainnet Beta exit gates</Link><a href="https://x.com/hoodfloow" target="_blank" rel="noreferrer">𝕏 @hoodfloow</a></footer>
  </main>;
}
